name: Email Smoke Gmail

on:
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send test email via Gmail SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}   # smtp.gmail.com
          server_port: ${{ secrets.SMTP_PORT }}        # 587
          username: ${{ secrets.SMTP_USER }}           # your Gmail address
          password: ${{ secrets.SMTP_PASS }}           # 16-char Gmail App Password
          subject: Gmail SMTP Smoke
          to: mona.ghadiri@outlook.com
          from: ${{ secrets.SMTP_USER }}
          body: |
            This is a Gmail SMTP smoke test from GitHub Actions.
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
