name: RunTrader
on:
  workflow_dispatch: {}          # run manually from your phone

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (fast)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt || true
          python -m pip install "openai>=1.30.0" yfinance

      - name: Run trading + graph
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python "Start Your Own/Trading_Script.py"
          python "Start Your Own/Generate_Graph.py" || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            **/*.png
            **/*.csv
            **/*.txt
          if-no-files-found: ignore
